spring:
  application:
    name: rest-with-spring-boot-and-java-leonardo
  datasource:
    url: jdbc:postgresql://localhost:5432/db-curso-java-basico-udemy
    username: leonardosilva
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect não é necessário declarar esse dialect mais, o próprio spring pediu para remover
    show-sql: false
    open-in-view: false
logging:
  level:
    #root: WARN #dessa maneira limitamos a aplicação por inteira e a pasta br.com.leeo_s com um nível diferente
    #configurar logs globais economizam recursos, mostrando somente o que é importante para o dev
    # TRACE -> DEBUG -> INFO -> WARN -> ERROR (sequencia de ordenação dos logs)
    br.com.leeo_s: DEBUG
